# Generated by Django 4.0.6 on 2022-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.SmallIntegerField(null=True),
        ),
    ]
