# Generated by Django 4.0.6 on 2022-07-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0003_alter_book_author_alter_book_is_in_print_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_cover_url',
            new_name='image',
        ),
    ]
