# Generated by Django 4.0.6 on 2022-07-19 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0004_rename_book_cover_url_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
