# Generated by Django 4.0.6 on 2022-07-21 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0009_genre_issue_bookreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookReview',
        ),
    ]
