# Generated by Django 4.0.6 on 2022-07-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_app', '0012_author_name_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='magazines', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
