# Generated by Django 4.0.6 on 2022-07-22 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books_app', '0013_magazine_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by_this_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
