# Generated by Django 4.0.6 on 2022-07-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0014_alter_bookreview_reviewer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='title',
            new_name='issue_num',
        ),
    ]
